GET http://localhost:5278/cities
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNzExNTYzNjM5LCJleHAiOjE3MTE1NjcyMzksImlhdCI6MTcxMTU2MzYzOX0.-LuQfEXU8dorW1kXblK9coqqkcR5J_NiW6gRyr7qfqs



###
GET http://localhost:5278/cities/3



###
GET http://localhost:5278/flights
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNzExNjI2MjUyLCJleHAiOjE3MTE2Mjk4NTIsImlhdCI6MTcxMTYyNjI1MiwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.aXxpiI5cuaVh_ErPZuUCMwFDPdpTRIisFo-NLm0zYKs



###
GET http://localhost:5278/flights/7



###
POST http://localhost:5278/flights
Authorization: Bearer 
Content-Type: application/json

{
    "DepartureCityId": 3,
    "ArrivalCityId":1,
    "departureDate": "2024-05-26",
    "numberOfConnections": 2,
    "availableSeatsCount": 12
  }

###
PUT http://localhost:5278/flights/7
Content-Type: application/json

{
    "departureCityId": 3,
    "arrivalCityId": 1,
    "departureDate": "2024-03-25",
    "numberOfConnections": 0,
    "availableSeatsCount": 12
  }

###
DELETE http://localhost:5278/flights/5

###
POST http://localhost:5278/login
Content-Type: application/json

{
    "Username": "admin",
    "Password": "admin"
  }

  ###
  POST http://localhost:5278/users
Authorization: "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImFkbWluIiwicm9sZSI6ImFkbWluIiwibmJmIjoxNzEyMTgxNTQxLCJleHAiOjE3MTIxODUxNDEsImlhdCI6MTcxMjE4MTU0MSwiaXNzIjoiZG90bmV0LXVzZXItand0cyJ9.fdq4kFcgV6WQG5lK_xRgUd7uEZQitI85G8L56GGlpEY"
Content-Type: application/json

{
    "Username": "visitor9",
    "Password":"visitor9",
    "Role": "visitor",
  }